# Generated by Django 3.2.4 on 2021-06-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalCrud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dueDate',
            field=models.DateField(null=True),
        ),
    ]
