# Generated by Django 3.2.4 on 2021-06-20 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generalCrud', '0002_alter_task_duedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='isCalendarHeadline',
        ),
        migrations.AddField(
            model_name='event',
            name='dateClass',
            field=models.CharField(default='month', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='generalCrud.event'),
        ),
    ]
